### ISSUE TITLE
Prevent "transitive" duplicates

### ISSUE THREAD

**Issue by mattyg** [commons-stack/praise#394] opened 2022-05-12 16:47 UTC
When marking a praise as duplicate, it must not be considered the "original" of another duplicate praise.

**Steps to reproduce**
On QuantifyTable, given the following praise in order: [ A, B, C ]
- Check praise B
- Check praise C
- click "mark duplicates"
- confirm
- Check praise A
- Check praise B
- click "mark duplicates"
- confirm

**Praise B will be a duplicate of praise A, and praise C will be a duplicate of Praise B**

**Comment by kristoferlund** [comment] 2022-05-18 10:59
How is this handled by the scoring algorithm currently? Perhaps it would be easiest to return an error if this occurs? If you mark a praise a duplicate of a praise that also is marked as a duplicate then error.

**Comment by mattyg** [comment] 2022-05-18 17:21
> How is this handled by the scoring algorithm currently? Perhaps it would be easiest to return an error if this occurs? If you mark a praise a duplicate of a praise that also is marked as a duplicate then error.

I think Praise C would receive a score of 0. Yeah I agree the `quantify` controller should throw an error preventing this.

**Closed** 2022-05-26 09:00 UTC
Labels: bug, api, frontend
